#pragma once

#define USBHMIDI_NAMESPACE usbHostMidi
#define BEGIN_USBHMIDI_NAMESPACE \
	    namespace USBHMIDI_NAMESPACE \
		{
#define END_USBHMIDI_NAMESPACE }

#define USING_NAMESPACE_USBHMIDI using namespace USBHMIDI_NAMESPACE;

BEGIN_USBHMIDI_NAMESPACE

END_USBHMIDI_NAMESPACE
